import { useEffect, useMemo, useState } from 'react'
import { Navigate, NavLink, Outlet, Route, Routes, useLocation, useNavigate, useParams } from 'react-router-dom'
import { BookOpen, ChartNoAxesCombined, ChevronRight, ClipboardList, FileText, GraduationCap, LayoutDashboard, LogOut, Menu, Search, ShieldAlert, SlidersHorizontal, UserRound, Users, X } from 'lucide-react'
import { useAuth } from './context/AuthContext'
import { getStudent, getStudentRecord, getStudents } from './services/studentService'
import { getCourses } from './services/courseService'
import { getCreditPolicies } from './services/creditPolicyService'
import { getCreditBands } from './services/creditBandService'
import { getCompetencyAnalyses } from './services/analysisService'
import { supabase } from './lib/supabase'

const studentNav = [
  ['Overview', '/student', LayoutDashboard], ['My Profile', '/student/profile', UserRound], ['My Courses', '/student/courses', BookOpen], ['My Competency', '/student/competency', ChartNoAxesCombined], ['Course Information', '/courses', BookOpen], ['Credit Allocation Bands', '/credit-bands', SlidersHorizontal], ['Methodology', '/methodology', FileText],
]
const facultyNav = [
  ['Overview', '/faculty', LayoutDashboard], ['Students', '/faculty/students', Users], ['Courses', '/faculty/courses', BookOpen], ['Competency Analysis', '/faculty/analysis', ChartNoAxesCombined], ['Credit Comparison', '/faculty/credits', SlidersHorizontal], ['Credit Policies', '/faculty/policies', FileText], ['Credit Allocation Bands', '/credit-bands', SlidersHorizontal], ['Course Outcomes', '/faculty/outcomes', ClipboardList], ['Cohort Analytics', '/faculty/analytics', ChartNoAxesCombined], ['Methodology', '/methodology', FileText],
]

function ProtectedRoute({ children, role }) {
  const auth = useAuth()
  if (auth.loading) return <Loading message="Restoring your session..." />
  if (!auth.user) return <Navigate to="/login" replace />
  if (!auth.role) return <ProfilePending />
  if (role && auth.role !== role) return <Unauthorized />
  return children
}

function AppLayout() {
  const auth = useAuth(); const location = useLocation(); const navigate = useNavigate(); const [open, setOpen] = useState(false)
  const isFaculty = auth.role === 'faculty'; const nav = isFaculty ? facultyNav : studentNav
  const title = location.pathname === '/student' || location.pathname === '/faculty' ? 'Overview' : nav.find((item) => location.pathname.startsWith(item[1]))?.[0] ?? 'Academic system'
  return <div className="app-shell">
    <aside className={open ? 'sidebar open' : 'sidebar'}>
      <div className="brand"><div className="brand-mark">CSP</div><div><strong>Competency-Based</strong><span>Credit System</span></div><button className="icon-button mobile-close" onClick={() => setOpen(false)} aria-label="Close navigation"><X size={18} /></button></div>
      <div className="role-label">{isFaculty ? 'Faculty workspace' : 'Student workspace'}</div>
      <nav aria-label="Primary navigation">{nav.map(([label, path, Icon]) => <NavLink key={path} to={path} end={path === '/student' || path === '/faculty'} onClick={() => setOpen(false)}><Icon size={17} /><span>{label}</span></NavLink>)}</nav>
      <div className="sidebar-footer"><div className="identity"><div className="avatar">{(auth.user?.email?.[0] ?? 'U').toUpperCase()}</div><div><strong>{auth.user?.email?.split('@')[0]}</strong><span>{auth.role}</span></div></div><button className="signout" onClick={async () => { await auth.signOut(); navigate('/login') }}><LogOut size={16} /> Sign out</button></div>
    </aside>
    <main className="main-content"><header className="topbar"><button className="icon-button mobile-menu" onClick={() => setOpen(true)} aria-label="Open navigation"><Menu size={20} /></button><div><p className="eyebrow">CSP / {isFaculty ? 'FACULTY' : 'STUDENT'}</p><h1>{title}</h1></div><div className="topbar-meta"><span className="status-dot" /> Authenticated session</div></header><div className="page-content"><Outlet /></div></main>
  </div>
}

function Login() {
  const auth = useAuth(); const navigate = useNavigate(); const [mode, setMode] = useState('signIn'); const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [error, setError] = useState(''); const [message, setMessage] = useState(''); const [busy, setBusy] = useState(false)
  if (auth.loading) return <Loading message="Loading CSP..." />
  if (auth.user) return <Navigate to={auth.role === 'faculty' ? '/faculty' : '/student'} replace />
  async function submit(event) { event.preventDefault(); setError(''); setMessage(''); setBusy(true); try { if (mode === 'signIn') { await auth.signIn(email.trim(), password); navigate('/'); } else { const result = await auth.signUp(email.trim(), password); if (result.session) navigate('/'); else setMessage(`Account created for ${email.trim().replace(/@klu\.ac\.in$/i, '')}@klu.ac.in. Check your university email to confirm your account.`) } } catch (problem) { setError(problem.message || `Unable to ${mode === 'signIn' ? 'sign in' : 'create your account'}.`) } finally { setBusy(false) } }
  function switchMode(nextMode) { setMode(nextMode); setError(''); setMessage('') }
  const isSignIn = mode === 'signIn'
  return <main className="login-page"><section className="login-panel"><div className="brand login-brand"><div className="brand-mark">CSP</div><div><strong>Competency-Based</strong><span>Credit System</span></div></div><div className="login-copy"><p className="eyebrow">UNIVERSITY ACADEMIC SYSTEM</p><h1>{isSignIn ? 'Academic insight, grounded in evidence.' : 'Create your academic access.'}</h1><p>{isSignIn ? 'Sign in with your university email to access your authorized academic records.' : 'Enter your register number. CSP will use it as your university email and match your academic record.'}</p></div><div className="auth-tabs" role="tablist" aria-label="Authentication options"><button className={isSignIn ? 'auth-tab active' : 'auth-tab'} onClick={() => switchMode('signIn')} type="button" role="tab" aria-selected={isSignIn}>Sign in</button><button className={!isSignIn ? 'auth-tab active' : 'auth-tab'} onClick={() => switchMode('signUp')} type="button" role="tab" aria-selected={!isSignIn}>Create account</button></div><form onSubmit={submit}><label htmlFor="email">{isSignIn ? 'University email' : 'Register number'}</label><input id="email" type={isSignIn ? 'email' : 'text'} value={email} onChange={(event) => setEmail(event.target.value)} placeholder={isSignIn ? 'registernumber@klu.ac.in' : 'Register number'} autoComplete={isSignIn ? 'email' : 'username'} required />{!isSignIn && <p className="field-note">Your university email will be {email.trim().replace(/@klu\.ac\.in$/i, '') || 'registernumber'}@klu.ac.in</p>}<label htmlFor="password">Password</label><input id="password" type="password" value={password} onChange={(event) => setPassword(event.target.value)} autoComplete={isSignIn ? 'current-password' : 'new-password'} minLength={6} required />{error && <div className="form-error" role="alert">{error}</div>}{message && <div className="form-message" role="status">{message}</div>}<button className="primary-button" disabled={busy || !supabase}>{busy ? (isSignIn ? 'Signing in...' : 'Creating account...') : (isSignIn ? 'Sign in' : 'Create account')}<ChevronRight size={17} /></button>{!supabase && <p className="config-note">Supabase configuration is missing. Add the VITE environment variables to enable authentication.</p>}</form><p className="login-foot">Access is governed by your university role and database permissions.</p></section></main>
}

function StudentDashboard({ faculty = false }) {
  const auth = useAuth(); const [student, setStudent] = useState(null); const [record, setRecord] = useState(null); const [status, setStatus] = useState('loading')
  useEffect(() => { if (faculty) return; Promise.all([getStudent(auth.studentId), getStudentRecord(auth.studentId)]).then(([studentResult, recordResult]) => { setStudent(studentResult.data); setRecord(recordResult.data); setStatus(studentResult.error ? 'error' : 'ready') }) }, [auth.studentId, faculty])
  if (faculty) return <FacultyDashboard />
  if (status === 'loading') return <Loading message="Loading student information..." />
  if (status === 'error') return <ErrorState message="Unable to load student information." />
  const courses = Array.isArray(record?.completed_courses) ? record.completed_courses : []
  return <><PageIntro eyebrow="PERSONAL ACADEMIC RECORD" title={`Welcome, ${student?.student_name ?? 'student'}`} description="Your academic standing, course history, and competency-based credit record." /><div className="metric-grid">{[['Student ID', student?.student_id], ['Program', student?.program], ['Batch', student?.batch_year], ['Current semester', student?.current_semester], ['CGPA', student?.cgpa], ['Credits earned', student?.credits_earned], ['Credits studied', student?.credits_studied], ['Credits remaining', student?.credits_to_be_earned], ['Arrears', student?.arrears_count]].map(([label, value]) => <Metric key={label} label={label} value={value ?? '—'} />)}</div><div className="content-grid"><section className="panel"><SectionHeading title="Academic overview" meta={`${courses.length} completed courses`} /><div className="mini-list">{courses.slice(0, 4).map((course) => <div className="mini-row" key={`${course.semester}-${course.course_code}`}><div><strong>{course.course_code}</strong><span>{course.course_name}</span></div><span className="grade">{course.grade}</span></div>)}{courses.length === 0 && <EmptyState title="No course history available" detail="Completed course records will appear here when provided by the academic system." />}</div></section><section className="panel"><SectionHeading title="Competency overview" meta="Current status" /><EmptyState title="Analysis not available yet" detail="Competency performance data is not available yet." /><NavLink className="text-link" to="/student/competency">View competency record <ChevronRight size={15} /></NavLink></section></div></>
}

function FacultyDashboard() { const [stats, setStats] = useState({ students: '—', courses: '—', policies: '—', analyses: '—' }); useEffect(() => { Promise.all([getStudents({ to: 0 }), getCourses(), getCreditPolicies(), getCompetencyAnalyses()]).then(([students, courses, policies, analyses]) => setStats({ students: students.count ?? students.data?.length ?? '—', courses: courses.data?.length ?? '—', policies: policies.data?.filter((item) => item.status === 'active').length ?? '—', analyses: analyses.data?.length ?? '—' })) }, []); return <><PageIntro eyebrow="FACULTY RESEARCH WORKSPACE" title="Academic overview" description="A measured view of academic performance, competency evidence, and credit allocation." /><div className="metric-grid four">{[['Total students', stats.students], ['Total courses', stats.courses], ['Active policies', stats.policies], ['Competency analyses', stats.analyses]].map(([label, value]) => <Metric key={label} label={label} value={value} />)}</div><div className="content-grid"><section className="panel"><SectionHeading title="Analysis readiness" meta="System status" /><div className="readiness"><div><span className="status-dot" /><strong>Academic source connected</strong></div><p>Course configuration and student records are queried directly from the authorized academic tables.</p><div><span className="status-dot muted" /><strong>Competency dataset pending</strong></div><p>Charts and credit allocation results will populate when competency performance data is available.</p></div></section><section className="panel"><SectionHeading title="Research workflow" meta="Method" /><ol className="workflow"><li>Course configuration</li><li>Student performance</li><li>Weighted competency score</li><li>Course-level percentile</li><li>Credit allocation band</li></ol><NavLink className="text-link" to="/methodology">Read methodology <ChevronRight size={15} /></NavLink></section></div></> }

function StudentsPage() { const [students, setStudents] = useState([]); const [search, setSearch] = useState(''); const [status, setStatus] = useState('loading'); useEffect(() => { setStatus('loading'); getStudents({ search }).then(({ data, error }) => { setStudents(data ?? []); setStatus(error ? 'error' : 'ready') }) }, [search]); return <><PageIntro eyebrow="FACULTY / STUDENTS" title="Student directory" description="Search the authorized student population and open a complete academic profile." /><div className="toolbar"><div className="search-field"><Search size={17} /><input aria-label="Search students" placeholder="Search by name or student ID" value={search} onChange={(event) => setSearch(event.target.value)} /></div><button className="secondary-button"><SlidersHorizontal size={16} /> Filters</button></div>{status === 'loading' ? <Loading message="Loading student records..." /> : status === 'error' ? <ErrorState message="Unable to load student records." /> : <DataTable columns={['Student ID', 'Student name', 'Program', 'Batch', 'Semester', 'CGPA', 'Status']} rows={students.map((student) => [student.student_id, <NavLink className="table-link" to={`/faculty/students/${student.id}`}>{student.student_name}</NavLink>, student.program, student.batch_year, student.current_semester, student.cgpa, <span className="tag">{student.status}</span>])} empty="No students match this search." />}</> }

function StudentProfile() { const { studentId } = useParams(); const [student, setStudent] = useState(null); const [record, setRecord] = useState(null); useEffect(() => { Promise.all([getStudent(studentId), getStudentRecord(studentId)]).then(([one, two]) => { setStudent(one.data); setRecord(two.data) }) }, [studentId]); if (!student) return <Loading message="Loading student profile..." />; const courses = Array.isArray(record?.completed_courses) ? record.completed_courses : []; return <><PageIntro eyebrow="FACULTY VIEW / STUDENT PROFILE" title={student.student_name} description={`Academic record for ${student.student_id}. This view is available to authorized faculty.`} /><div className="metric-grid four">{[['Program', student.program], ['Batch', student.batch_year], ['CGPA', student.cgpa], ['Credits earned', student.credits_earned]].map(([label, value]) => <Metric label={label} value={value ?? '—'} key={label} />)}</div><section className="panel"><SectionHeading title="Completed courses" meta={`${courses.length} records`} /><DataTable columns={['Semester', 'Course code', 'Course name', 'Credits', 'Grade', 'Year']} rows={courses.map((course) => [course.semester, course.course_code, course.course_name, course.credits, course.grade, course.year_of_passing])} empty="No completed courses available." /></section></> }

function CoursesPage() { const [courses, setCourses] = useState([]); const [search, setSearch] = useState(''); useEffect(() => { getCourses().then(({ data }) => setCourses(data ?? [])) }, []); const filteredCourses = useMemo(() => { const term = search.trim().toLowerCase(); if (!term) return courses; return courses.filter((course) => [course.course_code, course.course_name, course.department, course.course_type].some((value) => String(value ?? '').toLowerCase().includes(term))) }, [courses, search]); return <><PageIntro eyebrow="COURSE CATALOG" title="Course information" description="All courses available in the academic course table, with database-driven configuration and competency weightings." /><div className="toolbar"><div className="search-field"><Search size={17} /><input aria-label="Search courses" placeholder="Search by code, name, department, or type" value={search} onChange={(event) => setSearch(event.target.value)} /></div><span className="toolbar-count">{filteredCourses.length} of {courses.length} courses</span></div><DataTable columns={['Code', 'Course name', 'Department', 'Semester', 'Type', 'Reference', 'Range', 'Required']} rows={filteredCourses.map((course) => [course.course_code, course.course_name, course.department, course.semester, course.course_type, course.reference_credits, `${course.min_credits}–${course.max_credits}`, `${course.competency_required}%`])} empty="No courses match your search." /></> }
function MyCoursesPage() { const auth = useAuth(); const [courses, setCourses] = useState([]); const [status, setStatus] = useState('loading'); useEffect(() => { if (!auth.studentId) return; getStudentRecord(auth.studentId).then(({ data, error }) => { setCourses(Array.isArray(data?.completed_courses) ? data.completed_courses : []); setStatus(error ? 'error' : 'ready') }) }, [auth.studentId]); return <><PageIntro eyebrow="MY ACADEMIC RECORD" title="Completed courses" description="Courses recorded as completed in your academic history." />{status === 'loading' ? <Loading message="Loading completed courses..." /> : status === 'error' ? <ErrorState message="Unable to load your completed courses." /> : <DataTable columns={['Semester', 'Course code', 'Course name', 'Credits', 'Grade', 'Year of passing']} rows={courses.map((course) => [course.semester, course.course_code, course.course_name, course.credits, course.grade, course.year_of_passing])} empty="No completed courses recorded." />}</> }
function CompetencyPage() { const auth = useAuth(); const [groups, setGroups] = useState({ Advanced: [], Proficient: [], 'Basic competency': [], 'Not proficient': [] }); const [status, setStatus] = useState('loading'); useEffect(() => { if (!auth.studentId) return; getStudentRecord(auth.studentId).then((recordResult) => { if (recordResult.error) { setStatus('error'); return } const completed = Array.isArray(recordResult.data?.completed_courses) ? recordResult.data.completed_courses : []; const nextGroups = { Advanced: [], Proficient: [], 'Basic competency': [], 'Not proficient': [] }; completed.forEach((course) => { const grade = String(course.grade ?? '').trim().toUpperCase(); const category = grade === 'S' || grade === 'A' ? 'Advanced' : (grade === 'B' || grade === 'C') ? 'Proficient' : (grade === 'D' || grade === 'E') ? 'Basic competency' : 'Not proficient'; nextGroups[category].push({ course, grade }) }); setGroups(nextGroups); setStatus('ready') }) }, [auth.studentId]); if (status === 'loading') return <Loading message="Loading competency classification..." />; if (status === 'error') return <ErrorState message="Unable to load competency information." />; return <><PageIntro eyebrow="MY COMPETENCY" title="Competency classification" description="Courses are classified only from your completed_courses academic record using the recorded base grade." /><div className="competency-groups"><CompetencyGroup title="Advanced competency" detail="Base grade S or A" items={groups.Advanced} completed /><CompetencyGroup title="Proficient competency" detail="Base grade B or C" items={groups.Proficient} completed /><CompetencyGroup title="Basic competency" detail="Base grade D or E" items={groups['Basic competency']} completed /><CompetencyGroup title="Not proficient" detail="Any other completed-course grade" items={groups['Not proficient']} completed /></div></> }
function CompetencyGroup({ title, detail, items }) { return <section className="panel competency-group"><SectionHeading title={title} meta={`${items.length} courses`} /><p className="group-detail">{detail}</p>{items.length === 0 ? <EmptyState title="No courses in this group" detail="The group will populate from your completed_courses academic record." /> : <div className="competency-list">{items.map((item, index) => <div className="competency-row" key={`${item.course.course_code}-${index}`}><div><strong>{item.course.course_code}</strong><span>{item.course.course_name}</span><small>Base grade: {item.grade}</small></div><span className="credit-note">{item.course.credits ?? '—'} credits</span></div>)}</div>}</section> }
function CreditBandsPage() { const [bands, setBands] = useState([]); const [status, setStatus] = useState('loading'); useEffect(() => { getCreditBands().then(({ data, error }) => { setBands(data ?? []); setStatus(error ? 'error' : 'ready') }) }, []); return <><PageIntro eyebrow="CREDIT ALLOCATION" title="Credit allocation bands" description="Percentile ranges and awarded credits defined by the academic policy tables." />{status === 'loading' ? <Loading message="Loading credit allocation bands..." /> : status === 'error' ? <ErrorState message="Unable to load credit allocation bands." /> : <DataTable columns={['Reference credits', 'Percentile range', 'Credits awarded', 'Band name']} rows={bands.map((band) => [band.reference_credits, `${band.percentile_min}% – ${band.percentile_max}%`, band.credits_awarded, band.band_name])} empty="No credit allocation bands available." />}</> }

function SimplePage({ title, eyebrow, description, children }) { return <><PageIntro eyebrow={eyebrow} title={title} description={description} />{children ?? <section className="panel"><EmptyState title="No records available yet" detail="This area is ready for the next authorized academic dataset." /></section>}</> }
function Methodology() { return <SimplePage eyebrow="SYSTEM METHOD" title="Research methodology" description="The calculation path from course configuration to competency-based credits."><section className="method-grid">{['Course configuration', 'Student performance', 'Weighted competency score', 'Course-level percentile', 'Credit allocation band', 'Dynamic credits', 'Reference vs dynamic comparison'].map((step, index) => <div className="method-step" key={step}><span>{String(index + 1).padStart(2, '0')}</span><strong>{step}</strong><p>{index === 2 ? 'Course percentages weight theory, practical, hands-on, and project scores.' : index === 4 ? 'A matching policy band determines the credits awarded for the course.' : 'Authorized academic data moves to the next stage of the analysis.'}</p></div>)}</section></SimplePage> }
function Unauthorized() { return <main className="center-state"><ShieldAlert size={34} /><h1>Access restricted</h1><p>Your account does not have permission to view this academic area.</p><NavLink className="primary-button compact" to="/">Return to overview</NavLink></main> }
function ProfilePending() { const auth = useAuth(); return <main className="center-state"><UserRound size={34} /><h1>Account awaiting academic access</h1><p>{auth.user?.email} is authenticated, but no student or faculty profile is linked yet. Ask your university administrator to verify your register number.</p><button className="primary-button compact" onClick={auth.signOut}>Sign out</button></main> }
function Loading({ message }) { return <div className="state"><div className="loader" /><span>{message}</span></div> }
function ErrorState({ message }) { return <div className="state error-state"><ShieldAlert size={19} /><span>{message}</span></div> }
function EmptyState({ title, detail }) { return <div className="empty"><div className="empty-mark">—</div><strong>{title}</strong><p>{detail}</p></div> }
function Metric({ label, value }) { return <div className="metric"><span>{label}</span><strong>{value}</strong></div> }
function PageIntro({ eyebrow, title, description }) { return <div className="page-intro"><p className="eyebrow">{eyebrow}</p><h2>{title}</h2><p>{description}</p></div> }
function SectionHeading({ title, meta }) { return <div className="section-heading"><h3>{title}</h3><span>{meta}</span></div> }
function DataTable({ columns, rows, empty }) { return <div className="table-wrap"><table><thead><tr>{columns.map((column) => <th key={column}>{column}</th>)}</tr></thead><tbody>{rows.length ? rows.map((row, index) => <tr key={index}>{row.map((cell, cellIndex) => <td key={cellIndex}>{cell}</td>)}</tr>) : <tr><td colSpan={columns.length}><EmptyState title={empty} detail="Try another search or check back after the next data import." /></td></tr>}</tbody></table></div> }

function App() { return <Routes><Route path="/login" element={<Login />} /><Route element={<ProtectedRoute><AppLayout /></ProtectedRoute>}><Route index element={<RoleHome />} /><Route path="student" element={<RoleGate role="student"><RoleHome /></RoleGate>} /><Route path="student/profile" element={<RoleGate role="student"><StudentDashboard /></RoleGate>} /><Route path="student/competency" element={<RoleGate role="student"><CompetencyPage /></RoleGate>} /><Route path="student/courses" element={<RoleGate role="student"><MyCoursesPage /></RoleGate>} /><Route path="courses" element={<CoursesPage />} /><Route path="credit-bands" element={<CreditBandsPage />} /><Route path="methodology" element={<Methodology />} /><Route path="faculty" element={<RoleGate role="faculty"><RoleHome /></RoleGate>} /><Route path="faculty/students" element={<RoleGate role="faculty"><StudentsPage /></RoleGate>} /><Route path="faculty/students/:studentId" element={<RoleGate role="faculty"><StudentProfile /></RoleGate>} /><Route path="faculty/courses" element={<RoleGate role="faculty"><CoursesPage /></RoleGate>} /><Route path="faculty/analysis" element={<RoleGate role="faculty"><SimplePage eyebrow="FACULTY / ANALYSIS" title="Competency analysis" description="Course-level competency performance and allocation results." /></RoleGate>} /><Route path="faculty/credits" element={<RoleGate role="faculty"><SimplePage eyebrow="FACULTY / CREDITS" title="Credit comparison" description="Reference credits compared with competency-based allocations." /></RoleGate>} /><Route path="faculty/policies" element={<RoleGate role="faculty"><SimplePage eyebrow="FACULTY / POLICIES" title="Credit policies" description="Active and historical allocation policy definitions." /></RoleGate>} /><Route path="faculty/outcomes" element={<RoleGate role="faculty"><SimplePage eyebrow="FACULTY / OUTCOMES" title="Course outcomes" description="Evidence and weighting for each course outcome." /></RoleGate>} /><Route path="faculty/analytics" element={<RoleGate role="faculty"><SimplePage eyebrow="FACULTY / COHORT ANALYTICS" title="Cohort analytics" description="Aggregate distributions without unnecessary student-identifying data." /></RoleGate>} /></Route><Route path="*" element={<Navigate to="/" replace />} /></Routes> }
function RoleHome() { const auth = useAuth(); return <StudentDashboard faculty={auth.role === 'faculty'} /> }
function RoleGate({ role, children }) { const auth = useAuth(); return auth.role === role ? children : <Unauthorized /> }

export default App